### PR TITLE
Fix custom sounds in Shiny.Notification on Android, see issue #461

### LINKED ISSUE #461: [v2][Android] Custom sound
# Custom sound is broken on Android in 2.0.0 pre-release (dev branch)

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

## Feature Library

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Shiny.Notifications 2.0.0.2356-preview (also with v2.0.0.2285-preview)

## Version of OS(s) listed above with issue
* Android 8 to 11

## Steps to Reproduce
1. Send notification with custom sound (like done in shinysamples with "notification.mp3")

## Expected Behavior
Android notification **plays custom sound**.

## Actual Behavior
Android notification **plays default sound**.

Actually there are two problems:

**Problem 1:** custom sound path is not correctly mapped to resource URI.
The system cannot find the sound resource, e.g. on Android 6:
```
MediaPlayer Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /raw/alarm_siren
MediaPlayer Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /raw/alarm_siren
RingtonePlayer error loading sound for /raw/alarm_siren
RingtonePlayer  java.io.IOException: setDataSource failed.
RingtonePlayer error loading sound for /raw/alarm_siren
RingtonePlayer  java.io.IOException: setDataSource failed.
```

Shiny passes sound path given by the user in ``Notification.Sound.CustomPath`` directly to ``Uri.Parse()`` which obviously leads to an URI that cannot be correctly mapped to a resource by Android.

**Problem 2:** Since Android 8 (Oreo) the sounds are tied to the notification channel when the channel is created. The user can override the sound in the App notification settings anytime. To change the sound programmatically you have to e.g. uninstall and reinstall the app.

Shiny currently configures the sound on the notification channel **after** the channel was created. This has no effect even when calling ``NotificationManager.CreateNotificationChannel()`` again. Deleting the notification channel before recreating it also does not help.

### PR DESCRIPTION
**Pull request by cpraehaus**
### Description of Change ###

Two changes to Android NotificationManager in Shiny.Notification:
- Generate and use custom sound URI of the form *android.resource://<PKG_NAME>/raw/<RES_NAME>* (e.g. *android.resource://com.shiny.sample/raw/notification*) that allows Android to access the Apps' sound resource (see issue description).
- Call SetSound() with custom sound **before** notification channel is created
    NOTE: currently this also sets the vibration mode but I think thats OK

Note that custom sounds on Android 8 and above are only set properly
when the notification channel is created. Changing the sound later
in the Notification will have no effect until the App is re-installed (uninstalled and the installed again).
There might be other workaround too which I don't know of.

### Issues Resolved ### 

- fixes #461 

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral Changes ###
None

### Testing Procedure ###

* Tested manually on Android 5.1, 6, 9 and 11
* Can be tested with shinysamples app (need to include notification.mp3 resource though)

### PR Checklist ###

- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

File: src/Shiny.Notifications/Platforms/Android/NotificationManager.cs [hunk 1]
```diff
@@ -229,18 +246,18 @@ protected virtual void CreateChannel(Notification notification)
                 if (!d.IsEmpty())
                     channel.Description = d;
 
-                this.manager.CreateNotificationChannel(channel);
-            }
+                // Set initial sound attributes for channel when it is created
+                if (notification.Sound?.IsCustomSound() ?? false)
```
Comment (aritchie) [inline src/Shiny.Notifications/Platforms/Android/NotificationManager.cs:250]: The minlevel check should not be removed

**Comment by aritchie** [comment]
This isn't going to fix the issue with the ability to change the sound.  The channel customizations and way they are managed will have to be changed, but that is an issue for me to look into.

File: src/Shiny.Notifications/Platforms/Android/NotificationManager.cs (hunk 1 above)
Comment (cpraehaus) [reply src/Shiny.Notifications/Platforms/Android/NotificationManager.cs:250]: The minlevel is already checked at the beginning of the ``CreateChannel`` method so I thought its not necessary below:
(https://github.com/shinyorg/shiny/blob/35e58343af92392d770a8d64f0e9660830bab430/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs#L232

**Comment by cpraehaus** [comment]
> This isn't going to fix the issue with the ability to change the sound. The channel customizations and way they are managed will have to be changed, but that is an issue for me to look into.

True and I explicitly stated that in my comments. It will be challenging to find a consistent solution that works well across platforms with the "limitations" of the notification channel on Android. In the end, App developers shouldn't rely too much on properties of notification channel anyway, since the Android user can control and change a lot (not only the notification sound) - this is a feature of Android. Therefore, IMO, Shiny should not tempt developers to override (notification) settings the user has explicitly set: this would be a quite annoying experience for users.

**Comment by aritchie** [comment]
Thanks for the PR.  I'll end up taking this in a few days.  I think I have a few ideas around adding a channel portion for the API that works on iOS and Android.  iOS has categories which are different but still force a static model on things similar to android channels
